"""
Fix organization type misclassifications using rule-based patterns.

Uses the same logic as qc_org_types.py but applies fixes to the database.
"""

import os
import csv
import time
from dotenv import load_dotenv
load_dotenv('.env.local')

from supabase import create_client

print("=" * 70)
print("FIX ORGANIZATION TYPE CLASSIFICATIONS")
print("=" * 70)

# Connect
print("\nConnecting to Supabase...")
supabase = create_client(
    os.environ['NEXT_PUBLIC_SUPABASE_URL'],
    os.environ['SUPABASE_SERVICE_KEY']
)
print("✓ Connected\n")

# Read mismatches from CSV (generated by qc_org_types.py)
input_file = 'org_type_mismatches.csv'
if not os.path.exists(input_file):
    print(f"✗ Error: {input_file} not found!")
    print("  Run: python3 etl/qc_org_types.py first")
    exit(1)

# Load mismatches
print(f"Reading {input_file}...")
mismatches = []
with open(input_file, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        mismatches.append(row)

print(f"✓ Loaded {len(mismatches):,} mismatches to fix\n")

# Group by expected type for reporting
by_expected = {}
for m in mismatches:
    exp = m['expected']
    by_expected[exp] = by_expected.get(exp, 0) + 1

print("Summary of fixes to apply:")
for exp, count in sorted(by_expected.items(), key=lambda x: -x[1]):
    print(f"  → {exp}: {count:,} projects")

# Confirm
print("\nApplying fixes...")

# Apply fixes in batches
fixed = 0
errors = 0
batch_size = 100

for i in range(0, len(mismatches), batch_size):
    batch = mismatches[i:i+batch_size]

    for m in batch:
        try:
            supabase.table('projects').update({
                'org_type': m['expected']
            }).eq('application_id', m['application_id']).execute()
            fixed += 1
        except Exception as e:
            errors += 1
            if errors <= 5:
                print(f"  Error fixing {m['application_id']}: {e}")

    print(f"  Fixed {fixed:,} / {len(mismatches):,} projects", end='\r', flush=True)
    time.sleep(0.05)  # Small delay to avoid rate limits

print(f"\n\n✓ Fixed {fixed:,} projects")
if errors > 0:
    print(f"✗ Errors: {errors}")

# Show final distribution
print("\n" + "=" * 70)
print("FINAL ORG_TYPE DISTRIBUTION")
print("=" * 70)

for org_type in ['university', 'hospital', 'research_institute', 'company', 'government', 'other']:
    result = supabase.table('projects').select('application_id', count='exact').eq('org_type', org_type).execute()
    print(f"  {org_type:20} {result.count:>8,}")

print("=" * 70)
